### ISSUE TITLE
Getting error on android: "The model is INCOMPATIBLE. It may contain unrecognized custom ops, or not FlatBuffer format"

### ISSUE THREAD

**Issue by yashcfg** [tulasiram58827/ocr_tflite#12]
I am trying to convert my _keras-ocr_ keras model into **tflite** format for my android project.

I ran [this](https://github.com/tulasiram58827/ocr_tflite/blob/main/colabs/KERAS_OCR_TFLITE.ipynb) notebook (locally as well as on colab) but the output **tflite** does not work on android. It throws error - 

```
E/CustomCompatChecker: The model is INCOMPATIBLE. It may contain unrecognized custom ops, or not FlatBuffer format: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 34 (FlexRelu6) failed to prepare.
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: games.cloudfeather.mlkitcustom2, PID: 4111
    com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.ml.common.FirebaseMLException: Model is not compatible with TFLite run time
        at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
        at games.cloudfeather.mlkitcustom2.MainActivity$2$1.onComplete(MainActivity.java:59)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: com.google.firebase.ml.common.FirebaseMLException: Model is not compatible with TFLite run time
        at com.google.firebase.ml.common.internal.modeldownload.zzab.zza(com.google.firebase:firebase-ml-common@@22.1.2:59)
        at com.google.firebase.ml.common.internal.modeldownload.zzai.zzat(com.google.firebase:firebase-ml-common@@22.1.2:47)
        at com.google.firebase.ml.common.internal.modeldownload.zzai.load(com.google.firebase:firebase-ml-common@@22.1.2:18)
        at com.google.android.gms.internal.firebase_ml.zzri.zza(com.google.firebase:firebase-ml-model-interpreter@@22.0.4:32)
        at com.google.android.gms.internal.firebase_ml.zzro.call(Unknown Source:4)
        at com.google.android.gms.internal.firebase_ml.zzqf.zza(com.google.firebase:firebase-ml-common@@22.1.2:32)
        at com.google.android.gms.internal.firebase_ml.zzqe.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process: Sending signal. PID: 4111 SIG: 9

```

However when I use pre-built **tflite** files from [this](https://github.com/tulasiram58827/ocr_tflite/tree/main/models) folder, everything works.

Is there any specific version using which these **tflite** files were converted? Because for me it is not working.

Thanks

**Comment by yashcfg** [comment]
Resolved this by adding 

```
dependencies {
    ...
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.4.0'
}
```

in _build.gradle_ (app level)
